from __future__ import annotations

import os
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from pygenesis.config.loader import ConfigLoader
from pygenesis.models.config import ProjectConfig
from pygenesis.render.engine import RenderEngine
from pygenesis.utils.files import FileUtils


class ProjectGenerator:
    def __init__(self, templates_dir: str | Path | None = None) -> None:
        if templates_dir is None:
            templates_dir = Path(__file__).resolve().parents[1] / "templates"
        self.templates_dir = Path(templates_dir)

    def generate(self, config: ProjectConfig, output_dir: str | Path) -> Path:
        base = Path(output_dir).resolve()
        out = base / config.project.name
        FileUtils.ensure_dir(out)

        context = self._build_context(config)

        template_dir = self.templates_dir / config.template.value
        if not template_dir.is_dir():
            raise FileNotFoundError(
                f"Template not found: {template_dir} "
                f"(available: {self._list_templates()})"
            )

        self.renderer = RenderEngine(template_dir)
        self._render_template(template_dir, out, context)

        return out

    def generate_from_yaml(self, yaml_path: str | Path, output_dir: str | Path) -> Path:
        config = ConfigLoader.load(yaml_path)
        return self.generate(config, output_dir)

    def _build_context(self, config: ProjectConfig) -> dict[str, Any]:
        now = datetime.now(UTC)
        return {
            "project": config.project,
            "author": config.author,
            "github": config.github,
            "license": config.license.value,
            "debian": config.debian,
            "python": config.python,
            "module_name": config.module_name,
            "debian_package": config.debian_package,
            "github_url": config.github_url,
            "github_repo": config.github_repo,
            "description": f"Generated by PyGenesis — {config.project.name}",
            "year": str(now.year),
            "date": now.strftime("%Y-%m-%d"),
            "date_rfc2822": now.strftime("%a, %d %b %Y %H:%M:%S +0000"),
        }

    def _render_template(
        self, template_dir: Path, output_dir: Path, context: dict[str, Any]
    ) -> None:
        for item in template_dir.rglob("*"):
            if item.is_dir():
                continue
            relative = item.relative_to(template_dir)

            rendered_path = self._render_path(str(relative), context)
            dest = output_dir / rendered_path

            if item.suffix == ".jinja":
                dest = dest.with_suffix("")
                dest = Path(re.sub(r"\.jinja$", "", str(dest)))
                content = self.renderer.render_file(str(relative), context)
                FileUtils.write_file(dest, content)
                if item.name == "rules":
                    os.chmod(dest, 0o755)
            else:
                content = item.read_text(encoding="utf-8")
                content = self._render_if_needed(content, context)
                FileUtils.write_file(dest, content)

    def _render_path(self, path: str, context: dict[str, Any]) -> str:
        pattern = r"\{\{(.*?)\}\}"
        def replacer(m: re.Match[str]) -> str:
            key = m.group(1).strip()
            val = context.get(key, f"{{{{ {key} }}}}")
            return str(val)
        return re.sub(pattern, replacer, path)

    def _render_if_needed(self, content: str, context: dict[str, Any]) -> str:
        if "{{" in content and "}}" in content:
            return self.renderer.render_string(content, context)
        return content

    def _list_templates(self) -> list[str]:
        if not self.templates_dir.is_dir():
            return []
        return [d.name for d in self.templates_dir.iterdir() if d.is_dir()]
